// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CheckUfmSyntaxData, CheckUfmSyntaxErrors, CheckUfmSyntaxResponses, ConvertBlockLabelsData, ConvertBlockLabelsErrors, ConvertBlockLabelsResponses, EvaluateBlockLabelsData, EvaluateBlockLabelsErrors, EvaluateBlockLabelsResponses, PingData, PingErrors, PingResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class UmbracoFlavoredMarkdownExtensionsService {
    public static checkUfmSyntax<ThrowOnError extends boolean = false>(options?: Options<CheckUfmSyntaxData, ThrowOnError>): RequestResult<CheckUfmSyntaxResponses, CheckUfmSyntaxErrors, ThrowOnError> {
        return (options?.client ?? client).get<CheckUfmSyntaxResponses, CheckUfmSyntaxErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/ufmextensions/api/v1/checkUfmSyntax',
            ...options
        });
    }
    
    public static convertBlockLabels<ThrowOnError extends boolean = false>(options?: Options<ConvertBlockLabelsData, ThrowOnError>): RequestResult<ConvertBlockLabelsResponses, ConvertBlockLabelsErrors, ThrowOnError> {
        return (options?.client ?? client).post<ConvertBlockLabelsResponses, ConvertBlockLabelsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/ufmextensions/api/v1/convertBlockLabelsToUfm',
            ...options
        });
    }
    
    public static evaluateBlockLabels<ThrowOnError extends boolean = false>(options?: Options<EvaluateBlockLabelsData, ThrowOnError>): RequestResult<EvaluateBlockLabelsResponses, EvaluateBlockLabelsErrors, ThrowOnError> {
        return (options?.client ?? client).get<EvaluateBlockLabelsResponses, EvaluateBlockLabelsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/ufmextensions/api/v1/evaluateBlockLabelsToUfm',
            ...options
        });
    }
    
    public static ping<ThrowOnError extends boolean = false>(options?: Options<PingData, ThrowOnError>): RequestResult<PingResponses, PingErrors, ThrowOnError> {
        return (options?.client ?? client).get<PingResponses, PingErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/ufmextensions/api/v1/ping',
            ...options
        });
    }
}
