// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44365' | (string & {});
};

export type BlockLabelChange = {
    dataTypeName: string;
    block: string;
    property: string;
    originalLabel: string;
    convertedLabel: string;
    status: string;
    applied: boolean;
    warnings: Array<string>;
};

export type BlockLabelUfmReport = {
    dryRun: boolean;
    useDragonflyUfmComponents: boolean;
    dataTypesScanned: number;
    dataTypesSaved: number;
    readonly labelsNeedingReviewCount: number;
    readonly labelsConvertedCount: number;
    readonly labelsUnchangedCount: number;
    labelsNeedingReview: Array<BlockLabelChange>;
    labelsConverted: Array<BlockLabelChange>;
    labelsUnchanged: Array<BlockLabelChange>;
};

export type BlockLabelUfmReportWritable = {
    dryRun: boolean;
    useDragonflyUfmComponents: boolean;
    dataTypesScanned: number;
    dataTypesSaved: number;
    labelsNeedingReview: Array<BlockLabelChange>;
    labelsConverted: Array<BlockLabelChange>;
    labelsUnchanged: Array<BlockLabelChange>;
};

export type ConvertBlockLabelsData = {
    body?: never;
    path?: never;
    query?: {
        UseDragonflyUfmComponents?: boolean;
    };
    url: '/umbraco/ufmextensions/api/v1/convertBlockLabelsToUfm';
};

export type ConvertBlockLabelsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ConvertBlockLabelsResponses = {
    /**
     * OK
     */
    200: BlockLabelUfmReport;
};

export type ConvertBlockLabelsResponse = ConvertBlockLabelsResponses[keyof ConvertBlockLabelsResponses];

export type EvaluateBlockLabelsData = {
    body?: never;
    path?: never;
    query?: {
        UseDragonflyUfmComponents?: boolean;
    };
    url: '/umbraco/ufmextensions/api/v1/evaluateBlockLabelsToUfm';
};

export type EvaluateBlockLabelsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type EvaluateBlockLabelsResponses = {
    /**
     * OK
     */
    200: BlockLabelUfmReport;
};

export type EvaluateBlockLabelsResponse = EvaluateBlockLabelsResponses[keyof EvaluateBlockLabelsResponses];

export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ufmextensions/api/v1/ping';
};

export type PingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PingResponses = {
    /**
     * OK
     */
    200: string;
};

export type PingResponse = PingResponses[keyof PingResponses];
