// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44365' | (string & {});
};

export type BlockLabelChange = {
    dataTypeName: string;
    block: string;
    property: string;
    originalLabel: string;
    convertedLabel: string;
    status: string;
    applied: boolean;
    warnings: Array<string>;
};

export type BlockLabelUfmReport = {
    dryRun: boolean;
    useContentTypeNameComponent: boolean;
    dataTypesScanned: number;
    dataTypesSaved: number;
    labelsConverted: number;
    labelsNeedingReview: number;
    labelsUnchanged: number;
    changes: Array<BlockLabelChange>;
};

export type PreviewBlockLabelConversionData = {
    body?: never;
    path?: never;
    query?: {
        UseContentTypeNameComponent?: boolean;
    };
    url: '/umbraco/ufmextensions/api/v1/convertBlockLabelsToUfm';
};

export type PreviewBlockLabelConversionErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PreviewBlockLabelConversionResponses = {
    /**
     * OK
     */
    200: BlockLabelUfmReport;
};

export type PreviewBlockLabelConversionResponse = PreviewBlockLabelConversionResponses[keyof PreviewBlockLabelConversionResponses];

export type ConvertBlockLabelsData = {
    body?: never;
    path?: never;
    query?: {
        UseContentTypeNameComponent?: boolean;
    };
    url: '/umbraco/ufmextensions/api/v1/convertBlockLabelsToUfm';
};

export type ConvertBlockLabelsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ConvertBlockLabelsResponses = {
    /**
     * OK
     */
    200: BlockLabelUfmReport;
};

export type ConvertBlockLabelsResponse = ConvertBlockLabelsResponses[keyof ConvertBlockLabelsResponses];

export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ufmextensions/api/v1/ping';
};

export type PingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PingResponses = {
    /**
     * OK
     */
    200: string;
};

export type PingResponse = PingResponses[keyof PingResponses];
